Makefile: fix ld error
for some reason standard ld requires -lm to be at the end of the line

/usr/bin/ld: /tmp/ccz0frbx.o: in function `lenValue':
main.c:(.text+0x17): undefined reference to `log10'
/usr/bin/ld: /tmp/ccz0frbx.o: in function `toSensibleUnit':
main.c:(.text+0x108): undefined reference to `log10'

Signed-off-by: Skyblueborb <tomaszborbely0710@gmail.com>